=== DAM1-COTARELO-25-26/proyecto-web-cacique-500/datos/tienda.dtd
<!ELEMENT tienda_alcohol (alcoholes)>
<!ELEMENT alcoholes (alcohol_no_premium, alcohol_premium)>

<!ELEMENT alcohol_no_premium (rones, Whiskey, Licores_Gallegos, ginebra)>
<!ELEMENT alcohol_premium (rones, Whiskey, ginebra)>

<!ELEMENT rones (Barcelo | Cazique | Bumbu | Old_harper | La_Recompensa | Santa_Teresa | Barcelo_Imperial | Cazique_500 | Bumbu_Dark | Havana_Club | La_Santisima_Trinidad | Santa_Teresa_1976)*>
<!ELEMENT Whiskey (Red_Label | Ballantains | Almirate | Matt_Ken | Pipers_100 | Black_Elephant | Black_Label | Jack_Daniels | Jack_Daniels_Honey | Green_Label | Blue_Label | Cardu)*>
<!ELEMENT Licores_Gallegos (Licorca | Crema_de_Orujo | Crema_de_Whiskey | Crema_de_Chocolate | Licor_de_Hierbas | Licor_de_Cereza)*>
<!ELEMENT ginebra (Dagger | Beefeater | Larios | Glivery | Hendriks | Bulldog | Martin_Millers | The_London)*>

<!ENTITY % attrs "
    precio CDATA #REQUIRED
    disponible (TRUE | FALSE) #REQUIRED">

<!ELEMENT Barcelo (#PCDATA)> <!ATTLIST Barcelo %attrs;>
<!ELEMENT Cazique (#PCDATA)> <!ATTLIST Cazique %attrs;>
<!ELEMENT Bumbu (#PCDATA)> <!ATTLIST Bumbu %attrs;>
<!ELEMENT Old_harper (#PCDATA)> <!ATTLIST Old_harper %attrs;>
<!ELEMENT La_Recompensa (#PCDATA)> <!ATTLIST La_Recompensa %attrs;>
<!ELEMENT Santa_Teresa (#PCDATA)> <!ATTLIST Santa_Teresa %attrs;>
<!ELEMENT Red_Label (#PCDATA)> <!ATTLIST Red_Label %attrs;>
<!ELEMENT Ballantains (#PCDATA)> <!ATTLIST Ballantains %attrs;>
<!ELEMENT Almirate (#PCDATA)> <!ATTLIST Almirate %attrs;>
<!ELEMENT Matt_Ken (#PCDATA)> <!ATTLIST Matt_Ken %attrs;>
<!ELEMENT Pipers_100 (#PCDATA)> <!ATTLIST Pipers_100 %attrs;>
<!ELEMENT Black_Elephant (#PCDATA)> <!ATTLIST Black_Elephant %attrs;>
<!ELEMENT Licorca (#PCDATA)> <!ATTLIST Licorca %attrs;>
<!ELEMENT Crema_de_Orujo (#PCDATA)> <!ATTLIST Crema_de_Orujo %attrs;>
<!ELEMENT Crema_de_Whiskey (#PCDATA)> <!ATTLIST Crema_de_Whiskey %attrs;>
<!ELEMENT Crema_de_Chocolate (#PCDATA)> <!ATTLIST Crema_de_Chocolate %attrs;>
<!ELEMENT Licor_de_Hierbas (#PCDATA)> <!ATTLIST Licor_de_Hierbas %attrs;>
<!ELEMENT Licor_de_Cereza (#PCDATA)> <!ATTLIST Licor_de_Cereza %attrs;>
<!ELEMENT Dagger (#PCDATA)> <!ATTLIST Dagger %attrs;>
<!ELEMENT Beefeater (#PCDATA)> <!ATTLIST Beefeater %attrs;>
<!ELEMENT Larios (#PCDATA)> <!ATTLIST Larios %attrs;>
<!ELEMENT Glivery (#PCDATA)> <!ATTLIST Glivery %attrs;>
<!ELEMENT Barcelo_Imperial (#PCDATA)> <!ATTLIST Barcelo_Imperial %attrs;>
<!ELEMENT Cazique_500 (#PCDATA)> <!ATTLIST Cazique_500 %attrs;>
<!ELEMENT Bumbu_Dark (#PCDATA)> <!ATTLIST Bumbu_Dark %attrs;>
<!ELEMENT Havana_Club (#PCDATA)> <!ATTLIST Havana_Club %attrs;>
<!ELEMENT La_Santisima_Trinidad (#PCDATA)> <!ATTLIST La_Santisima_Trinidad %attrs;>
<!ELEMENT Santa_Teresa_1976 (#PCDATA)> <!ATTLIST Santa_Teresa_1976 %attrs;>
<!ELEMENT Black_Label (#PCDATA)> <!ATTLIST Black_Label %attrs;>
<!ELEMENT Jack_Daniels (#PCDATA)> <!ATTLIST Jack_Daniels %attrs;>
<!ELEMENT Jack_Daniels_Honey (#PCDATA)> <!ATTLIST Jack_Daniels_Honey %attrs;>
<!ELEMENT Green_Label (#PCDATA)> <!ATTLIST Green_Label %attrs;>
<!ELEMENT Blue_Label (#PCDATA)> <!ATTLIST Blue_Label %attrs;>
<!ELEMENT Cardu (#PCDATA)> <!ATTLIST Cardu %attrs;>
<!ELEMENT Hendriks (#PCDATA)> <!ATTLIST Hendriks %attrs;>
<!ELEMENT Bulldog (#PCDATA)> <!ATTLIST Bulldog %attrs;>
<!ELEMENT Martin_Millers (#PCDATA)> <!ATTLIST Martin_Millers %attrs;>
<!ELEMENT The_London (#PCDATA)> <!ATTLIST The_London %attrs;>

=== DAM1-COTARELO-25-26/proyecto-web-cacique-500/datos/alcoholes.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE tienda_alcohol SYSTEM "tienda.dtd">

<tienda_alcohol>
    <alcoholes>
        <alcohol_no_premium>
            <rones>
                <Barcelo precio="14.99€" disponible="TRUE">
                    Ron dominicano suave y equilibrado, con notas dulces y ligeros matices de vainilla. Ideal para combinados.
                </Barcelo>
                <Cazique precio="13.99€" disponible="TRUE">
                    Ron versátil de sabor ligero y agradable, perfecto para cócteles clásicos y mezclas refrescantes.
                </Cazique>
                <Bumbu precio="19.99€" disponible="TRUE">
                    Ron aromático con toques especiados y dulces, ideal para disfrutar solo o con hielo.
                </Bumbu>
                <Old_harper precio="4.99€" disponible="FALSE">
                    Ron económico de sabor suave, pensado para combinaciones sencillas y consumo informal.
                </Old_harper>
                <La_Recompensa precio="5.99€" disponible="FALSE">
                    Ron equilibrado con notas dulces y ligeras de madera, excelente para mezclas.
                </La_Recompensa>
                <Santa_Teresa precio="8.99€" disponible="TRUE">
                    Ron venezolano de cuerpo medio, con notas suaves de caramelo y madera.
                </Santa_Teresa>
            </rones>

            <Whiskey>
                <Red_Label precio="14.99€" disponible="TRUE">
                    Whisky escocés intenso y vibrante, con notas ahumadas y especiadas.
                </Red_Label>
                <Ballantains precio="12.99€" disponible="TRUE">
                    Whisky suave y equilibrado, con toques de miel y vainilla.
                </Ballantains>
                <Almirate precio="2.99€" disponible="TRUE">
                    Whisky ligero y accesible, ideal para mezclar.
                </Almirate>
                <Matt_Ken precio="6.99€" disponible="FALSE">
                    Whisky suave de sabor sencillo, perfecto para combinados económicos.
                </Matt_Ken>
                <Pipers_100 precio="12.99€" disponible="TRUE">
                    Whisky escocés con carácter afrutado y final ligeramente ahumado.
                </Pipers_100>
                <Black_Elephant precio="4.99€" disponible="TRUE">
                    Whisky suave con notas dulces y ligeros matices tostados.
                </Black_Elephant>
            </Whiskey>

            <Licores_Gallegos>
                <Licorca precio="14.99€" disponible="TRUE">
                    Licor tradicional gallego con sabor dulce y aromático.
                </Licorca>
                <Crema_de_Orujo precio="7.99€" disponible="TRUE">
                    Crema suave y dulce con base de orujo, perfecta como digestivo.
                </Crema_de_Orujo>
                <Crema_de_Whiskey precio="9.99€" disponible="TRUE">
                    Licor cremoso con sabor a whisky y notas de caramelo.
                </Crema_de_Whiskey>
                <Crema_de_Chocolate precio="15.99€" disponible="TRUE">
                    Licor dulce y cremoso con intenso sabor a chocolate.
                </Crema_de_Chocolate>
                <Licor_de_Hierbas precio="8.99€" disponible="TRUE">
                    Licor tradicional gallego con mezcla aromática de hierbas.
                </Licor_de_Hierbas>
                <Licor_de_Cereza precio="23.99€" disponible="TRUE">
                    Licor afrutado con sabor intenso y dulce a cereza.
                </Licor_de_Cereza>
            </Licores_Gallegos>

            <ginebra>
                <Dagger precio="1.99€" disponible="TRUE"> 
                    Ginebra de terrible sabor, es recomendado no temer a la muerte, esta opción solo ha de tomarse cuando no queda otra.
                </Dagger>
                <Beefeater precio="11.99€" disponible="FALSE">
                    Clásica ginebra londinense, seca y equilibrada con notas cítricas.
                </Beefeater>
                <Larios precio="6.99€" disponible="TRUE">
                    Ginebra mediterránea, fresca y suave, con toques cítricos.
                </Larios>
                <Glivery precio="7.99€" disponible="FALSE">
                    Ginebra aromática de perfil suave, perfecta para gin-tonics.
                </Glivery>
            </ginebra>
        </alcohol_no_premium>

        <alcohol_premium>
            <rones>
                <Barcelo_Imperial precio="29.99€" disponible="TRUE">
                    Ron premium dominicano, envejecido en barrica, con notas de vainilla y frutos secos.
                </Barcelo_Imperial>
                <Cazique_500 precio="27.99€" disponible="TRUE">
                    Ron venezolano elegante y complejo, con notas intensas de madera y especias.
                </Cazique_500>
                <Bumbu_Dark precio="29.99€" disponible="TRUE">
                    Ron oscuro premium con carácter especiado y notas dulces profundas.
                </Bumbu_Dark>
                <Havana_Club precio="22.99€" disponible="TRUE">
                    Ron cubano añejo, equilibrado y aromático, ideal para disfrutar solo o en cócteles.
                </Havana_Club>
                <La_Santisima_Trinidad precio="39.99€" disponible="TRUE">
                    Ron cubano exclusivo, suave y refinado con notas de roble y caramelo.
                </La_Santisima_Trinidad>
                <Santa_Teresa_1976 precio="23.99€" disponible="TRUE">
                    Ron venezolano premium, complejo y elegante con notas de frutos secos y madera.
                </Santa_Teresa_1976>
            </rones>

            <Whiskey>
                <Black_Label precio="29.99€" disponible="TRUE">
                    Whisky escocés de gran equilibrio, con notas ahumadas y toque de fruta madura.
                </Black_Label>
                <Jack_Daniels precio="20.99€" disponible="TRUE"> 
                    Whiskey americano suave con notas de vainilla y caramelo.
                </Jack_Daniels>
                <Jack_Daniels_Honey precio="20.99€" disponible="TRUE">
                    Variante dulce con miel natural y suave toque de whiskey.
                </Jack_Daniels_Honey>
                <Green_Label precio="66.99€" disponible="TRUE">
                    Whisky escocés de malta pura, intenso y complejo.
                </Green_Label>
                <Blue_Label precio="199.99€" disponible="TRUE">
                    Whisky escocés ultra premium, sofisticado y excepcionalmente suave.
                </Blue_Label>
                <Cardu precio="39.99€" disponible="TRUE">
                    Single malt escocés elegante, con notas afrutadas y final suave.
                </Cardu>
            </Whiskey>

            <ginebra>
                <Hendriks precio="39.99€" disponible="FALSE">
                    Ginebra premium con infusión de pepino y rosa, fresca y aromática.
                </Hendriks>
                <Bulldog precio="24.00€" disponible="FALSE">
                    Ginebra moderna con perfil especiado y elegante.
                </Bulldog>
                <Martin_Millers precio="32.00€" disponible="TRUE">
                    Ginebra artesanal suave y equilibrada, con notas cítricas limpias.
                </Martin_Millers>
                <The_London precio="37.99€" disponible="FALSE">
                    Ginebra premium estilo London Dry, intensa y refinada.
                </The_London>
            </ginebra>
        </alcohol_premium>
    </alcoholes>
</tienda_alcohol>
